config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { sessions: 'users/sessions' }, path: '/', path_names: { sign_in: 'login', sign_out: 'logout' }

  root "portfolios#index"
  get '/portfolios', to: 'portfolios#list'
  get '/portfolios/list', to: 'portfolios#list'
  get '/templates', to: 'templates#list'
  get '/templates/list', to: 'templates#list'
  post '/portfolios/change_default_portfolio', to: 'portfolios#change_default_portfolio'

  resources :portfolios
  resources :templates

  # resolve('Portfolio') { [:portfolio] }
  # get '/portfolios/new', to: 'portfolios#new'
  # put '/portfolios/create', to: 'portfolios#create'
  # get '/portfolios/edit', to: 'portfolios#edit'
  # post '/portfolios/update', to: 'portfolios#update'
  # delete '/portfolios/destroy', to: 'portfolios#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioBuilder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- bootstrap 5 start -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <!-- bootstrap 5 end -->

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <% if user_signed_in? %>
        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
          <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <%= link_to 'Home', {controller: :portfolios, action: :index}, class: 'navbar-brand' %>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <%= link_to 'Portfolios', portfolios_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Templates', templates_path, class: 'nav-link' %>
                </li>                
              </ul>
              <div class="d-flex">
                <%= button_to 'Log Out', destroy_user_session_path, class: 'btn btn-outline-success', method: :delete %>
              </div>
            </div>
          </div>
        </nav>
      <% end %>      
      <% if notice.present? %> 
        <p class="notice alert alert-success"><%= notice %></p>
      <% end %> 

      <% if alert.present? %> 
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>     
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/blank.html.erb
<%= yield %>